#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

PROJECT_ID="${PROJECT_ID:-omois-483220}"
ZONE="${ZONE:-us-central1-c}"
PREP_VM_NAME="${PREP_VM_NAME:-ewm-yearly10k-ssl4eo50k-prep-cpu}"
A100_VM_NAME="${A100_VM_NAME:-ewm-phase2-a100-80}"
DATA_DISK_NAME="${DATA_DISK_NAME:-ewm-yearly10k-ssl4eo50k-data}"
DATA_DISK_SIZE_GB="${DATA_DISK_SIZE_GB:-1000}"
PREP_MACHINE_TYPE="${PREP_MACHINE_TYPE:-e2-standard-8}"
PREP_BOOT_DISK_SIZE_GB="${PREP_BOOT_DISK_SIZE_GB:-100}"
DATA_DISK_DEVICE_NAME="${DATA_DISK_DEVICE_NAME:-ewm-training-data}"

OUTPUT_ROOT="${OUTPUT_ROOT:-/mnt/ewm-data-disk/ewm_prelim_yearly10k_ssl4eo50k_v1}"
WORK_DIR="${WORK_DIR:-${OUTPUT_ROOT}_work}"
YEARLY_RAW_ROOTS="${YEARLY_RAW_ROOTS:-gs://omois-earth-world-model-phase2-20260320-11728/earth_engine_exact_chip52w_batch100|gs://omois-earth-world-model-phase2-20260320-11728/ee_exact_chip52w_batch_1000_3000_v2|gs://omois-earth-world-model-phase2-20260320-11728/earth_engine_interactive_exact_chip_100_10000_v1/raw|gs://omois-earth-world-model-phase2-20260320-11728/earth_engine_interactive_exact_chip_10000_100000_v2/raw}"

YEARLY_NAME="${YEARLY_NAME:-yearly_10000}"
SSL4EO_NAME="${SSL4EO_NAME:-ssl4eo_50000}"
YEARLY_TRAIN_COUNT="${YEARLY_TRAIN_COUNT:-10000}"
YEARLY_VAL_COUNT="${YEARLY_VAL_COUNT:-256}"
SSL4EO_TRAIN_COUNT="${SSL4EO_TRAIN_COUNT:-50000}"
SSL4EO_VAL_COUNT="${SSL4EO_VAL_COUNT:-1024}"
YEARLY_WORKERS="${YEARLY_WORKERS:-4}"
YEARLY_METADATA_FLUSH_SIZE="${YEARLY_METADATA_FLUSH_SIZE:-64}"
YEARLY_GCS_DOWNLOAD_WORKERS="${YEARLY_GCS_DOWNLOAD_WORKERS:-8}"
YEARLY_GCS_DOWNLOAD_TIMEOUT_SEC="${YEARLY_GCS_DOWNLOAD_TIMEOUT_SEC:-180}"
YEARLY_GCS_DOWNLOAD_RETRIES="${YEARLY_GCS_DOWNLOAD_RETRIES:-3}"
YEARLY_GCS_TRANSFER_BACKEND="${YEARLY_GCS_TRANSFER_BACKEND:-gcloud}"
SSL4EO_WORKERS="${SSL4EO_WORKERS:-4}"
TOTAL_WORKER_BUDGET="${TOTAL_WORKER_BUDGET:-8}"

BOOTSTRAP_PREP_VM="${BOOTSTRAP_PREP_VM:-1}"
DETACH_PREP_RUN="${DETACH_PREP_RUN:-1}"
SKIP_LAUNCH_A100="${SKIP_LAUNCH_A100:-1}"
OVERWRITE="${OVERWRITE:-0}"

echo "[prep] Launching yearly+SSL4EO SSD build"
echo "[prep] PREP_VM_NAME=$PREP_VM_NAME"
echo "[prep] A100_VM_NAME=$A100_VM_NAME"
echo "[prep] DATA_DISK_NAME=$DATA_DISK_NAME"
echo "[prep] OUTPUT_ROOT=$OUTPUT_ROOT"
echo "[prep] YEARLY_TRAIN_COUNT=$YEARLY_TRAIN_COUNT YEARLY_VAL_COUNT=$YEARLY_VAL_COUNT"
echo "[prep] SSL4EO_TRAIN_COUNT=$SSL4EO_TRAIN_COUNT SSL4EO_VAL_COUNT=$SSL4EO_VAL_COUNT"
echo "[prep] YEARLY_WORKERS=$YEARLY_WORKERS YEARLY_METADATA_FLUSH_SIZE=$YEARLY_METADATA_FLUSH_SIZE YEARLY_GCS_TRANSFER_BACKEND=$YEARLY_GCS_TRANSFER_BACKEND YEARLY_GCS_DOWNLOAD_WORKERS=$YEARLY_GCS_DOWNLOAD_WORKERS SSL4EO_WORKERS=$SSL4EO_WORKERS TOTAL_WORKER_BUDGET=$TOTAL_WORKER_BUDGET"

env \
  PROJECT_ID="$PROJECT_ID" \
  ZONE="$ZONE" \
  PREP_VM_NAME="$PREP_VM_NAME" \
  A100_VM_NAME="$A100_VM_NAME" \
  DATA_DISK_NAME="$DATA_DISK_NAME" \
  DATA_DISK_SIZE_GB="$DATA_DISK_SIZE_GB" \
  PREP_MACHINE_TYPE="$PREP_MACHINE_TYPE" \
  PREP_BOOT_DISK_SIZE_GB="$PREP_BOOT_DISK_SIZE_GB" \
  DATA_DISK_DEVICE_NAME="$DATA_DISK_DEVICE_NAME" \
  OUTPUT_ROOT="$OUTPUT_ROOT" \
  WORK_DIR="$WORK_DIR" \
  YEARLY_RAW_ROOTS="$YEARLY_RAW_ROOTS" \
  YEARLY_NAME="$YEARLY_NAME" \
  SSL4EO_NAME="$SSL4EO_NAME" \
  YEARLY_TRAIN_COUNT="$YEARLY_TRAIN_COUNT" \
  YEARLY_VAL_COUNT="$YEARLY_VAL_COUNT" \
  YEARLY_WORKERS="$YEARLY_WORKERS" \
  YEARLY_METADATA_FLUSH_SIZE="$YEARLY_METADATA_FLUSH_SIZE" \
  YEARLY_GCS_DOWNLOAD_WORKERS="$YEARLY_GCS_DOWNLOAD_WORKERS" \
  YEARLY_GCS_DOWNLOAD_TIMEOUT_SEC="$YEARLY_GCS_DOWNLOAD_TIMEOUT_SEC" \
  YEARLY_GCS_DOWNLOAD_RETRIES="$YEARLY_GCS_DOWNLOAD_RETRIES" \
  YEARLY_GCS_TRANSFER_BACKEND="$YEARLY_GCS_TRANSFER_BACKEND" \
  SSL4EO_WORKERS="$SSL4EO_WORKERS" \
  TOTAL_WORKER_BUDGET="$TOTAL_WORKER_BUDGET" \
  SSL4EO_TRAIN_COUNT="$SSL4EO_TRAIN_COUNT" \
  SSL4EO_VAL_COUNT="$SSL4EO_VAL_COUNT" \
  BOOTSTRAP_PREP_VM="$BOOTSTRAP_PREP_VM" \
  DETACH_PREP_RUN="$DETACH_PREP_RUN" \
  SKIP_LAUNCH_A100="$SKIP_LAUNCH_A100" \
  OVERWRITE="$OVERWRITE" \
  bash "$PROJECT_ROOT/earth_world_model/scripts/gcp_prepare_prelim400_and_launch_on_a100.sh"
