#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DATA_ROOT_BASE="${DATA_ROOT_BASE:-/mnt/ewm-data-disk/ewm_prelim_yearly10k_ssl4eo50k_v1}"
DEFAULT_RUN_STAMP="$(date +%Y%m%d_%H%M%S)"
GCS_RUNS_ROOT="${GCS_RUNS_ROOT:-gs://omois-earth-world-model-phase2-20260320-11728/earth_world_model/runs/paper2_sigreg_selected_10000_50000_e8_b16_${DEFAULT_RUN_STAMP}}"
LOCAL_RUNS_ROOT="${LOCAL_RUNS_ROOT:-/tmp/${GCS_RUNS_ROOT##*/}}"
SKIP_SETUP_GPU="${SKIP_SETUP_GPU:-0}"
YEARLY_NAME="${YEARLY_NAME:-yearly_10000}"
SSL4EO_NAME="${SSL4EO_NAME:-ssl4eo_50000}"
YEARLY_TRAIN_MAX_SAMPLES="${YEARLY_TRAIN_MAX_SAMPLES:-10000}"
YEARLY_VAL_MAX_SAMPLES="${YEARLY_VAL_MAX_SAMPLES:-256}"
SSL4EO_TRAIN_MAX_SAMPLES="${SSL4EO_TRAIN_MAX_SAMPLES:-50000}"
SSL4EO_VAL_MAX_SAMPLES="${SSL4EO_VAL_MAX_SAMPLES:-1024}"
EWM_BATCH_SIZE="${EWM_BATCH_SIZE:-16}"
EWM_AUXILIARY_BATCH_SIZE="${EWM_AUXILIARY_BATCH_SIZE:-16}"
EWM_EVAL_BATCH_SIZE="${EWM_EVAL_BATCH_SIZE:-16}"
EWM_EPOCHS="${EWM_EPOCHS:-8}"
EWM_MIXED_STAGE_EPOCHS="${EWM_MIXED_STAGE_EPOCHS:-4}"
EWM_MIXED_STAGE_AUXILIARY_FRACTION="${EWM_MIXED_STAGE_AUXILIARY_FRACTION:-0.5}"
EWM_GRAD_BALANCE_PROBE_EVERY_STEPS="${EWM_GRAD_BALANCE_PROBE_EVERY_STEPS:-440}"
EWM_GRAD_BALANCE_PROBE_MAX_EVENTS="${EWM_GRAD_BALANCE_PROBE_MAX_EVENTS:-3}"
EWM_REGULARIZATION_PROBE_EVERY_STEPS="${EWM_REGULARIZATION_PROBE_EVERY_STEPS:-220}"
EWM_REGULARIZATION_PROBE_MAX_EVENTS="${EWM_REGULARIZATION_PROBE_MAX_EVENTS:-8}"
EWM_REG_CROSSCOV_MU="${EWM_REG_CROSSCOV_MU:-0.002}"
EWM_REG_CROSSCOV_MAX_SAMPLES="${EWM_REG_CROSSCOV_MAX_SAMPLES:-0}"
EWM_SUBCLIP_16_START="${EWM_SUBCLIP_16_START:-0}"
EWM_SUBCLIP_32_START="${EWM_SUBCLIP_32_START:-2}"
EWM_SUBCLIP_52_START="${EWM_SUBCLIP_52_START:-4}"
EWM_TUBELET_SIZE="${EWM_TUBELET_SIZE:-1}"
EWM_EVAL_CHECKPOINT_METRIC="${EWM_EVAL_CHECKPOINT_METRIC:-mean_masked_loss}"
EWM_EVAL_CHECKPOINT_MIN_EPOCH="${EWM_EVAL_CHECKPOINT_MIN_EPOCH:-5}"
FORCE_RERUN="${FORCE_RERUN:-0}"
BASE_CONFIG_PATH="${BASE_CONFIG_PATH:-$PROJECT_ROOT/earth_world_model/configs/dense_temporal_index_pilot400_vjepa21_unified_sigreg_1024_mixed_ssl4eo_cuda_gpu_vm.yaml}"

run_filtered_suite() {
  local run_id_filter="$1"
  local run_core_ablations="$2"
  local run_arch_ablations="$3"

  env \
    DATA_ROOT_BASE="$DATA_ROOT_BASE" \
    GCS_RUNS_ROOT="$GCS_RUNS_ROOT" \
    LOCAL_RUNS_ROOT="$LOCAL_RUNS_ROOT" \
    YEARLY_NAME="$YEARLY_NAME" \
    SSL4EO_NAME="$SSL4EO_NAME" \
    YEARLY_TRAIN_MAX_SAMPLES="$YEARLY_TRAIN_MAX_SAMPLES" \
    YEARLY_VAL_MAX_SAMPLES="$YEARLY_VAL_MAX_SAMPLES" \
    SSL4EO_TRAIN_MAX_SAMPLES="$SSL4EO_TRAIN_MAX_SAMPLES" \
    SSL4EO_VAL_MAX_SAMPLES="$SSL4EO_VAL_MAX_SAMPLES" \
    EWM_BATCH_SIZE="$EWM_BATCH_SIZE" \
    EWM_AUXILIARY_BATCH_SIZE="$EWM_AUXILIARY_BATCH_SIZE" \
    EWM_EVAL_BATCH_SIZE="$EWM_EVAL_BATCH_SIZE" \
    EWM_EPOCHS="$EWM_EPOCHS" \
    EWM_MIXED_STAGE_EPOCHS="$EWM_MIXED_STAGE_EPOCHS" \
    EWM_MIXED_STAGE_AUXILIARY_FRACTION="$EWM_MIXED_STAGE_AUXILIARY_FRACTION" \
    EWM_GRAD_BALANCE_PROBE_EVERY_STEPS="$EWM_GRAD_BALANCE_PROBE_EVERY_STEPS" \
    EWM_GRAD_BALANCE_PROBE_MAX_EVENTS="$EWM_GRAD_BALANCE_PROBE_MAX_EVENTS" \
    EWM_REGULARIZATION_PROBE_EVERY_STEPS="$EWM_REGULARIZATION_PROBE_EVERY_STEPS" \
    EWM_REGULARIZATION_PROBE_MAX_EVENTS="$EWM_REGULARIZATION_PROBE_MAX_EVENTS" \
    EWM_REG_CROSSCOV_MU="$EWM_REG_CROSSCOV_MU" \
    EWM_REG_CROSSCOV_MAX_SAMPLES="$EWM_REG_CROSSCOV_MAX_SAMPLES" \
    EWM_SUBCLIP_16_START="$EWM_SUBCLIP_16_START" \
    EWM_SUBCLIP_32_START="$EWM_SUBCLIP_32_START" \
    EWM_SUBCLIP_52_START="$EWM_SUBCLIP_52_START" \
    EWM_TUBELET_SIZE="$EWM_TUBELET_SIZE" \
    EWM_EVAL_CHECKPOINT_METRIC="$EWM_EVAL_CHECKPOINT_METRIC" \
    EWM_EVAL_CHECKPOINT_MIN_EPOCH="$EWM_EVAL_CHECKPOINT_MIN_EPOCH" \
    RUN_CORE_ABLATIONS="$run_core_ablations" \
    RUN_TIME_ABLATIONS=0 \
    RUN_ARCH_ABLATIONS="$run_arch_ablations" \
    RUN_ID_FILTER="$run_id_filter" \
    FORCE_RERUN="$FORCE_RERUN" \
    SKIP_SETUP_GPU="$SKIP_SETUP_GPU" \
    BASE_CONFIG_PATH="$BASE_CONFIG_PATH" \
    bash "$PROJECT_ROOT/earth_world_model/scripts/run_paper2_unified_suite_gpu_vm.sh"
}

run_filtered_suite "full_sigreg" "1" "0"
run_filtered_suite "global_sigreg" "1" "0"
run_filtered_suite "vicreg_per_subspace" "0" "1"
run_filtered_suite "ema_only" "1" "0"
