#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DATA_ROOT_BASE="${DATA_ROOT_BASE:-/mnt/ewm-data-disk/ewm_prelim_yearly10k_ssl4eo50k_v1}"
DEFAULT_RUN_STAMP="$(date +%Y%m%d_%H%M%S)"
GCS_RUNS_ROOT="${GCS_RUNS_ROOT:-gs://omois-earth-world-model-phase2-20260320-11728/earth_world_model/runs/paper2_factorized_world_model_selected_10000_50000_e8_b16_${DEFAULT_RUN_STAMP}}"
LOCAL_RUNS_ROOT="${LOCAL_RUNS_ROOT:-/tmp/${GCS_RUNS_ROOT##*/}}"
SKIP_SETUP_GPU="${SKIP_SETUP_GPU:-0}"
YEARLY_NAME="${YEARLY_NAME:-yearly_10000}"
SSL4EO_NAME="${SSL4EO_NAME:-ssl4eo_50000}"
YEARLY_TRAIN_MAX_SAMPLES="${YEARLY_TRAIN_MAX_SAMPLES:-10000}"
YEARLY_VAL_MAX_SAMPLES="${YEARLY_VAL_MAX_SAMPLES:-256}"
SSL4EO_TRAIN_MAX_SAMPLES="${SSL4EO_TRAIN_MAX_SAMPLES:-50000}"
SSL4EO_VAL_MAX_SAMPLES="${SSL4EO_VAL_MAX_SAMPLES:-1024}"
EWM_BATCH_SIZE="${EWM_BATCH_SIZE:-16}"
EWM_AUXILIARY_BATCH_SIZE="${EWM_AUXILIARY_BATCH_SIZE:-16}"
EWM_EVAL_BATCH_SIZE="${EWM_EVAL_BATCH_SIZE:-16}"
EWM_EPOCHS="${EWM_EPOCHS:-8}"
EWM_MIXED_STAGE_EPOCHS="${EWM_MIXED_STAGE_EPOCHS:-4}"
EWM_MIXED_STAGE_AUXILIARY_FRACTION="${EWM_MIXED_STAGE_AUXILIARY_FRACTION:-0.5}"
EWM_SUBCLIP_16_START="${EWM_SUBCLIP_16_START:-0}"
EWM_SUBCLIP_32_START="${EWM_SUBCLIP_32_START:-2}"
EWM_SUBCLIP_52_START="${EWM_SUBCLIP_52_START:-4}"
EWM_TUBELET_SIZE="${EWM_TUBELET_SIZE:-1}"
EWM_EVAL_CHECKPOINT_METRIC="${EWM_EVAL_CHECKPOINT_METRIC:-mean_masked_loss}"
EWM_EVAL_CHECKPOINT_MIN_EPOCH="${EWM_EVAL_CHECKPOINT_MIN_EPOCH:-5}"
FORCE_RERUN="${FORCE_RERUN:-0}"
RUN_ID_FILTER="${RUN_ID_FILTER:-}"
BASE_CONFIG_PATH="${BASE_CONFIG_PATH:-$PROJECT_ROOT/earth_world_model/configs/dense_temporal_index_pilot400_vjepa21_factorized_world_model_1024_mixed_ssl4eo_cuda_gpu_vm.yaml}"

env \
  DATA_ROOT_BASE="$DATA_ROOT_BASE" \
  GCS_RUNS_ROOT="$GCS_RUNS_ROOT" \
  LOCAL_RUNS_ROOT="$LOCAL_RUNS_ROOT" \
  YEARLY_NAME="$YEARLY_NAME" \
  SSL4EO_NAME="$SSL4EO_NAME" \
  YEARLY_TRAIN_MAX_SAMPLES="$YEARLY_TRAIN_MAX_SAMPLES" \
  YEARLY_VAL_MAX_SAMPLES="$YEARLY_VAL_MAX_SAMPLES" \
  SSL4EO_TRAIN_MAX_SAMPLES="$SSL4EO_TRAIN_MAX_SAMPLES" \
  SSL4EO_VAL_MAX_SAMPLES="$SSL4EO_VAL_MAX_SAMPLES" \
  EWM_BATCH_SIZE="$EWM_BATCH_SIZE" \
  EWM_AUXILIARY_BATCH_SIZE="$EWM_AUXILIARY_BATCH_SIZE" \
  EWM_EVAL_BATCH_SIZE="$EWM_EVAL_BATCH_SIZE" \
  EWM_EPOCHS="$EWM_EPOCHS" \
  EWM_MIXED_STAGE_EPOCHS="$EWM_MIXED_STAGE_EPOCHS" \
  EWM_MIXED_STAGE_AUXILIARY_FRACTION="$EWM_MIXED_STAGE_AUXILIARY_FRACTION" \
  EWM_SUBCLIP_16_START="$EWM_SUBCLIP_16_START" \
  EWM_SUBCLIP_32_START="$EWM_SUBCLIP_32_START" \
  EWM_SUBCLIP_52_START="$EWM_SUBCLIP_52_START" \
  EWM_TUBELET_SIZE="$EWM_TUBELET_SIZE" \
  EWM_EVAL_CHECKPOINT_METRIC="$EWM_EVAL_CHECKPOINT_METRIC" \
  EWM_EVAL_CHECKPOINT_MIN_EPOCH="$EWM_EVAL_CHECKPOINT_MIN_EPOCH" \
  FORCE_RERUN="$FORCE_RERUN" \
  RUN_ID_FILTER="$RUN_ID_FILTER" \
  SKIP_SETUP_GPU="$SKIP_SETUP_GPU" \
  BASE_CONFIG_PATH="$BASE_CONFIG_PATH" \
  bash "$PROJECT_ROOT/earth_world_model/scripts/run_paper2_factorized_world_model_suite_gpu_vm.sh"
